trigger:
- main

variables:
  github_repo: 'Ashwin-88/Ashwin-88.github.io'
  github_branch: 'main'

stages:
- stage: PushToGitHub
  jobs:
  - job: GitPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - checkout: self

    - script: |
        git config --global user.email "ci-bot@yourdomain.com"
        git config --global user.name "Azure DevOps Bot"

        # Add GitHub repo as remote
        git remote add github https://$(github_token)@github.com/$(github_repo)

        # Switch branch (create if missing)
        git fetch github
        git checkout $(github_branch) || git checkout -b $(github_branch)

        # Add and commit changes
        git add .
        git commit -m "Publish site from Azure DevOps CI" || echo "No changes to commit"

        # Push to GitHub Pages repo
        git push github $(github_branch) --force
      displayName: 'Publish to GitHub Pages'
